import { MockTherapist, MockReview, MockTestimonial, NavItem } from '@/types/customer';

export const NAV_LINKS: NavItem[] = [
  { label: 'Find a Therapist', href: '/find-a-therapist' },
  { label: 'Match Me', href: '/match-me' },
  { label: 'How It Works', href: '/#how-it-works' },
  { label: 'Reviews', href: '/#reviews' },
  { label: 'About', href: '/#about' },
];

export const MOCK_THERAPISTS: MockTherapist[] = [
  {
    id: 'therapist-1',
    name: 'Elena Rostova, LMT',
    title: 'Licensed Massage Therapist',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=600',
    galleryImages: [
      'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1519823551278-64ac92734fb1?auto=format&fit=crop&q=80&w=800',
    ],
    rating: 4.98,
    reviewCount: 142,
    location: 'Los Angeles, CA',
    serviceAreas: ['Santa Monica', 'Beverly Hills', 'Culver City', 'Los Angeles'],
    zipCodes: ['90210', '90401', '90230', '90001', '90028'],
    startingPrice: 120,
    availability: 'Available Today',
    offersStudio: true,
    offersInHome: true,
    specialties: ['Deep Tissue', 'Swedish', 'Sports Recovery', 'Trigger Point Therapy'],
    bio: 'Elena has over 9 years of clinical and restorative bodywork experience. She specializes in targeted deep tissue work combined with soothing Swedish techniques to alleviate chronic tension, improve mobility, and reduce stress.',
    experience: '9+ years in clinical massage therapy, sports injury rehabilitation centers, and luxury wellness studios across California.',
    approach: 'Every session begins with a brief postural assessment and conversation about your current stress levels, pain points, and mobility goals. Elena customizes pressure and focus areas to ensure both immediate therapeutic relief and long-term joint health.',
    services: [
      {
        id: 's1-1',
        name: 'Targeted Deep Tissue Massage',
        durationMinutes: 60,
        price: 120,
        description: 'Focused firm pressure targeting deep muscle layers and connective tissue to release chronic muscular knots.',
      },
      {
        id: 's1-2',
        name: 'Full Body Restorative Swedish',
        durationMinutes: 90,
        price: 165,
        description: 'Long gliding strokes with light to medium pressure designed to boost circulation, ease mental stress, and promote total body relaxation.',
      },
      {
        id: 's1-3',
        name: 'Sports Recovery & Mobility Session',
        durationMinutes: 90,
        price: 175,
        description: 'Dynamic stretching, myofascial release, and targeted muscle activation tailored for active individuals and athletes.',
      },
    ],
    schedule: [
      { days: 'Monday – Thursday', hours: '8:00 AM – 7:00 PM' },
      { days: 'Friday – Saturday', hours: '9:00 AM – 6:00 PM' },
      { days: 'Sunday', hours: '10:00 AM – 4:00 PM' },
    ],
    isMostBooked: true,
    isFeatured: true,
  },
  {
    id: 'therapist-2',
    name: 'Marcus Vance, LMT',
    title: 'Neuromuscular & Sports Specialist',
    image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=600',
    galleryImages: [
      'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1519823551278-64ac92734fb1?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&q=80&w=800',
    ],
    rating: 4.95,
    reviewCount: 98,
    location: 'New York, NY',
    serviceAreas: ['Manhattan', 'Brooklyn', 'Queens', 'New York'],
    zipCodes: ['10001', '10002', '11201', '10012', '10019'],
    startingPrice: 140,
    availability: 'Available Tomorrow',
    offersStudio: true,
    offersInHome: true,
    specialties: ['Sports Massage', 'Trigger Point', 'Myofascial Release', 'Postural Realignment'],
    bio: 'Marcus is a certified Neuromuscular Therapist with 11 years of experience working alongside physical therapists and endurance athletes. He focuses on postural alignment, acute injury recovery, and pain management.',
    experience: '11+ years working with collegiate athletes, marathon runners, and urban professionals dealing with postural strain.',
    approach: 'Marcus uses an evidence-informed approach that blends trigger point therapy, active resistance stretching, and myofascial release to restore range of motion and relieve stubborn aches.',
    services: [
      {
        id: 's2-1',
        name: 'Neuromuscular Pain Relief',
        durationMinutes: 60,
        price: 140,
        description: 'Systematic pressure applied to specific soft tissue triggers to relieve referred muscular pain and restore nerve pathway function.',
      },
      {
        id: 's2-2',
        name: 'Performance Sports Massage',
        durationMinutes: 90,
        price: 195,
        description: 'Pre or post-event bodywork aiming to reduce recovery times, break down scar tissue, and improve joint flexibility.',
      },
    ],
    schedule: [
      { days: 'Tuesday – Friday', hours: '7:30 AM – 8:00 PM' },
      { days: 'Saturday', hours: '8:00 AM – 5:00 PM' },
    ],
    isMostBooked: true,
    isFeatured: false,
  },
  {
    id: 'therapist-3',
    name: 'Sarah Chen, CMT',
    title: 'Holistic Bodywork Specialist',
    image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=600',
    galleryImages: [
      'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&q=80&w=800',
    ],
    rating: 5.0,
    reviewCount: 86,
    location: 'San Francisco, CA',
    serviceAreas: ['Downtown SF', 'SOMA', 'Marin County', 'San Francisco'],
    zipCodes: ['94102', '94103', '94901', '94107', '94109'],
    startingPrice: 130,
    availability: 'Available Today',
    offersStudio: true,
    offersInHome: false,
    specialties: ['Shiatsu', 'Prenatal Massage', 'Aromatherapy', 'Reflexology'],
    bio: 'Sarah is a holistic practitioner dedicated to integrative healing, prenatal care, and stress reduction through Eastern and Western massage techniques.',
    experience: '8 years of practice focusing on maternal wellness, stress relief, and mindful bodywork in San Francisco.',
    approach: 'Sarah provides a calming, meditative atmosphere incorporating gentle pressure points, organic essential oils, and tailored positioning for expectant mothers or client wellness goals.',
    services: [
      {
        id: 's3-1',
        name: 'Holistic Bodywork & Aromatherapy',
        durationMinutes: 75,
        price: 130,
        description: 'A harmonious blend of Swedish strokes, Shiatsu energy pathways, and custom botanical aromatherapy oils.',
      },
      {
        id: 's3-2',
        name: 'Gentle Prenatal Care Session',
        durationMinutes: 60,
        price: 135,
        description: 'Safe, comforting side-lying massage designed to ease pregnancy-related lumbar discomfort, swelling, and fatigue.',
      },
    ],
    schedule: [
      { days: 'Monday – Wednesday', hours: '9:00 AM – 6:00 PM' },
      { days: 'Friday – Saturday', hours: '10:00 AM – 5:00 PM' },
    ],
    isMostBooked: true,
    isFeatured: true,
  },
  {
    id: 'therapist-4',
    name: 'David Miller, LMT',
    title: 'Clinical & Orthopedic Therapist',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=600',
    galleryImages: [
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1519823551278-64ac92734fb1?auto=format&fit=crop&q=80&w=800',
    ],
    rating: 4.92,
    reviewCount: 114,
    location: 'Austin, TX',
    serviceAreas: ['Downtown Austin', 'Westlake', 'Round Rock', 'Austin'],
    zipCodes: ['78701', '78746', '78664', '78704', '78759'],
    startingPrice: 110,
    availability: 'Next Available Thursday',
    offersStudio: true,
    offersInHome: true,
    specialties: ['Therapeutic Massage', 'Deep Tissue', 'Reflexology', 'Myofascial Release'],
    bio: 'David combines clinical massage techniques with joint mobilization principles to help clients recover from desk posture fatigue and active movement stress.',
    experience: '7 years specializing in orthopedic soft-tissue assessment and desk-worker repetitive strain injury care.',
    approach: 'Focused on long-term relief and posture corrections, David assesses spinal alignment and upper body tension to tailor every minute of treatment.',
    services: [
      {
        id: 's4-1',
        name: 'Orthopedic & Clinical Massage',
        durationMinutes: 60,
        price: 110,
        description: 'Assessment-driven massage targeting chronic lower back, shoulder blade, and neck strain.',
      },
      {
        id: 's4-2',
        name: 'Extended Restorative Session',
        durationMinutes: 90,
        price: 150,
        description: 'Comprehensive full-body therapeutic care targeting multiple problem areas with deep tissue and reflexology.',
      },
    ],
    schedule: [
      { days: 'Thursday – Sunday', hours: '9:00 AM – 7:00 PM' },
    ],
    isMostBooked: false,
    isFeatured: true,
  },
  {
    id: 'therapist-5',
    name: 'Aaliyah Washington, LMT',
    title: 'Wellness & Lymphatic Specialist',
    image: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&q=80&w=600',
    galleryImages: [
      'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?auto=format&fit=crop&q=80&w=800',
    ],
    rating: 4.97,
    reviewCount: 73,
    location: 'Miami, FL',
    serviceAreas: ['Miami Beach', 'Brickell', 'Coral Gables', 'Miami'],
    zipCodes: ['33139', '33131', '33134', '33130', '33140'],
    startingPrice: 135,
    availability: 'Available Today',
    offersStudio: false,
    offersInHome: true,
    specialties: ['Lymphatic Drainage', 'Hot Stone', 'Swedish', 'Relaxation'],
    bio: 'Aaliyah brings spa-grade luxury directly to client homes, specializing in lymphatic drainage techniques, detox bodywork, and calming hot stone therapies.',
    experience: '6 years in high-end resort spas and private in-home mobile concierge therapy in South Florida.',
    approach: 'Prioritizing comfort and gentle circulation, Aaliyah blends rhythmic strokes with warming modalities for optimal immune system support and relaxation.',
    services: [
      {
        id: 's5-1',
        name: 'Manual Lymphatic Drainage',
        durationMinutes: 60,
        price: 135,
        description: 'Light, rhythmic movements designed to stimulate lymph flow, reduce fluid retention, and support post-travel recovery.',
      },
      {
        id: 's5-2',
        name: 'In-Home Warm Stone Massage',
        durationMinutes: 90,
        price: 180,
        description: 'Soothing heated basalt stones combined with rich botanical oils to melt muscular tension deeply.',
      },
    ],
    schedule: [
      { days: 'Monday – Saturday', hours: '10:00 AM – 8:00 PM' },
    ],
    isMostBooked: false,
    isFeatured: true,
  },
  {
    id: 'therapist-6',
    name: 'James Reynolds, LMT',
    title: 'Pain Management Specialist',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=600',
    galleryImages: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&q=80&w=800',
    ],
    rating: 4.89,
    reviewCount: 65,
    location: 'Chicago, IL',
    serviceAreas: ['Loop', 'Lincoln Park', 'Evanston', 'Chicago'],
    zipCodes: ['60601', '60614', '60201', '60611', '60657'],
    startingPrice: 125,
    availability: 'Available Friday',
    offersStudio: true,
    offersInHome: true,
    specialties: ['Medical Massage', 'Deep Tissue', 'Postural Realignment', 'Trigger Point'],
    bio: 'James works with clients managing chronic neck, shoulder, and sciatic discomfort using evidence-backed medical bodywork and myofascial release.',
    experience: '10 years collaborating with chiropractic clinics and private wellness practices in Chicago.',
    approach: 'Focuses on functional movement and tension reduction through systematic myofascial techniques and ergonomic education.',
    services: [
      {
        id: 's6-1',
        name: 'Targeted Medical Massage',
        durationMinutes: 60,
        price: 125,
        description: 'Focused clinical massage targeting specific medical or muscular conditions causing discomfort or stiffness.',
      },
      {
        id: 's6-2',
        name: 'Postural Realignment & Deep Work',
        durationMinutes: 90,
        price: 170,
        description: 'Comprehensive session combining deep tissue work and corrective stretching to improve posture and decrease tension.',
      },
    ],
    schedule: [
      { days: 'Wednesday – Sunday', hours: '9:00 AM – 6:00 PM' },
    ],
    isMostBooked: true,
    isFeatured: false,
  },
];

export const MOCK_TESTIMONIALS: MockTestimonial[] = [
  {
    id: 'test-1',
    customerName: 'Jennifer L.',
    customerLocation: 'Los Angeles, CA',
    rating: 5,
    title: 'Flawless In-Home Experience',
    comment: 'MASSAF made it so simple to find a vetted, professional therapist. Elena arrived on time with a full professional setup. Hands down the best deep tissue session I have had in years.',
    verifiedBooking: true,
    date: '2 days ago',
  },
  {
    id: 'test-2',
    customerName: 'Robert K.',
    customerLocation: 'New York, NY',
    rating: 5,
    title: 'Saved my lower back after marathon training',
    comment: 'The booking experience was effortless and transparent. Knowing therapists are background checked gave my family complete peace of mind.',
    verifiedBooking: true,
    date: '1 week ago',
  },
  {
    id: 'test-3',
    customerName: 'Amanda M.',
    customerLocation: 'San Francisco, CA',
    rating: 5,
    title: 'Clean, professional, and therapeutic',
    comment: 'I love being able to select between studio visits or in-home appointments. The quality of therapists on MASSAF is unmatched.',
    verifiedBooking: true,
    date: '2 weeks ago',
  },
];

export const MOCK_THERAPIST_REVIEWS: MockReview[] = [
  {
    id: 'rev-1',
    therapistId: 'therapist-1',
    therapistName: 'Elena Rostova, LMT',
    customerName: 'Michael B.',
    customerLocation: 'Santa Monica, CA',
    rating: 5,
    date: '2 days ago',
    comment: 'Elena listened attentively to my chronic neck strain issues and worked out tension I have carried for months. Exceptional professionalism.',
    serviceType: '90 Min Deep Tissue Massage',
  },
  {
    id: 'rev-1b',
    therapistId: 'therapist-1',
    therapistName: 'Elena Rostova, LMT',
    customerName: 'Sarah W.',
    customerLocation: 'Beverly Hills, CA',
    rating: 5,
    date: '1 week ago',
    comment: 'Brought her own clean table and crisp linens to my home in Beverly Hills. Punctual, polite, and extremely skilled in sports recovery work.',
    serviceType: '60 Min Targeted Deep Tissue',
  },
  {
    id: 'rev-1c',
    therapistId: 'therapist-1',
    therapistName: 'Elena Rostova, LMT',
    customerName: 'David K.',
    customerLocation: 'Culver City, CA',
    rating: 5,
    date: '2 weeks ago',
    comment: 'The Swedish restorative session was exactly what I needed after a brutal work week. I will definitely be a repeat client.',
    serviceType: '90 Min Full Body Restorative Swedish',
  },
  {
    id: 'rev-2',
    therapistId: 'therapist-2',
    therapistName: 'Marcus Vance, LMT',
    customerName: 'Sophia P.',
    customerLocation: 'Manhattan, NY',
    rating: 5,
    date: '3 days ago',
    comment: 'Marcus is a top-tier therapist. His knowledge of sports anatomy helped target my hamstrings perfectly.',
    serviceType: '60 Min Neuromuscular Pain Relief',
  },
  {
    id: 'rev-2b',
    therapistId: 'therapist-2',
    therapistName: 'Marcus Vance, LMT',
    customerName: 'Brian G.',
    customerLocation: 'Brooklyn, NY',
    rating: 5,
    date: '1 week ago',
    comment: 'Outstanding session. Released a lower back knot that was keeping me from running for 3 weeks.',
    serviceType: '90 Min Performance Sports Massage',
  },
  {
    id: 'rev-3',
    therapistId: 'therapist-3',
    therapistName: 'Sarah Chen, CMT',
    customerName: 'David H.',
    customerLocation: 'San Francisco, CA',
    rating: 5,
    date: '4 days ago',
    comment: 'Relaxing environment and masterful technique. Left feeling completely rejuvenated!',
    serviceType: '75 Min Holistic Bodywork',
  },
  {
    id: 'rev-3b',
    therapistId: 'therapist-3',
    therapistName: 'Sarah Chen, CMT',
    customerName: 'Rachel M.',
    customerLocation: 'San Francisco, CA',
    rating: 5,
    date: '2 weeks ago',
    comment: 'Sarah was wonderful for my third trimester prenatal session. Very attentive to body alignment and comfort.',
    serviceType: '60 Min Gentle Prenatal Care Session',
  },
  {
    id: 'rev-4',
    therapistId: 'therapist-4',
    therapistName: 'David Miller, LMT',
    customerName: 'Alex R.',
    customerLocation: 'Austin, TX',
    rating: 5,
    date: '5 days ago',
    comment: 'David fixed my desk posture neck pain in a single session. Highly recommended for desk workers in Austin!',
    serviceType: '60 Min Orthopedic & Clinical Massage',
  },
  {
    id: 'rev-5',
    therapistId: 'therapist-5',
    therapistName: 'Aaliyah Washington, LMT',
    customerName: 'Jessica T.',
    customerLocation: 'Miami, FL',
    rating: 5,
    date: '1 week ago',
    comment: 'The hot stone massage in my condo was like having a 5-star resort spa right in my living room.',
    serviceType: '90 Min In-Home Warm Stone Massage',
  },
  {
    id: 'rev-6',
    therapistId: 'therapist-6',
    therapistName: 'James Reynolds, LMT',
    customerName: 'Carlos M.',
    customerLocation: 'Chicago, IL',
    rating: 5,
    date: '6 days ago',
    comment: 'Very professional clinical approach. Helped me overcome persistent shoulder stiffness.',
    serviceType: '60 Min Targeted Medical Massage',
  },
];
