import { MockTherapist, MockReview, MockTestimonial, NavItem } from '@/types/customer';

export const NAV_LINKS: NavItem[] = [
  { label: 'Find a Therapist', href: '#search' },
  { label: 'How It Works', href: '#how-it-works' },
  { label: 'Reviews', href: '#reviews' },
  { label: 'About', href: '#about' },
];

export const MOCK_THERAPISTS: MockTherapist[] = [
  {
    id: 'therapist-1',
    name: 'Elena Rostova, LMT',
    title: 'Licensed Massage Therapist',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=600',
    rating: 4.98,
    reviewCount: 142,
    location: 'Los Angeles, CA',
    serviceAreas: ['Santa Monica', 'Beverly Hills', 'Culver City'],
    startingPrice: 120,
    availability: 'Available Today',
    offersStudio: true,
    offersInHome: true,
    specialties: ['Deep Tissue', 'Swedish', 'Sports Recovery'],
    isMostBooked: true,
    isFeatured: true,
  },
  {
    id: 'therapist-2',
    name: 'Marcus Vance, LMT',
    title: 'Neuromuscular & Sports Specialist',
    image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=600',
    rating: 4.95,
    reviewCount: 98,
    location: 'New York, NY',
    serviceAreas: ['Manhattan', 'Brooklyn', 'Queens'],
    startingPrice: 140,
    availability: 'Available Tomorrow',
    offersStudio: true,
    offersInHome: true,
    specialties: ['Sports Massage', 'Trigger Point', 'Myofascial Release'],
    isMostBooked: true,
    isFeatured: false,
  },
  {
    id: 'therapist-3',
    name: 'Sarah Chen, CMT',
    title: 'Holistic Bodywork Specialist',
    image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=600',
    rating: 5.0,
    reviewCount: 86,
    location: 'San Francisco, CA',
    serviceAreas: ['Downtown SF', 'SOMA', 'Marin County'],
    startingPrice: 130,
    availability: 'Available Today',
    offersStudio: true,
    offersInHome: false,
    specialties: ['Shiatsu', 'Prenatal Massage', 'Aromatherapy'],
    isMostBooked: true,
    isFeatured: true,
  },
  {
    id: 'therapist-4',
    name: 'David Miller, LMT',
    title: 'Clinical & Orthopedic Therapist',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=600',
    rating: 4.92,
    reviewCount: 114,
    location: 'Austin, TX',
    serviceAreas: ['Downtown Austin', 'Westlake', 'Round Rock'],
    startingPrice: 110,
    availability: 'Next Available Thursday',
    offersStudio: true,
    offersInHome: true,
    specialties: ['Therapeutic Massage', 'Deep Tissue', 'Reflexology'],
    isMostBooked: false,
    isFeatured: true,
  },
  {
    id: 'therapist-5',
    name: 'Aaliyah Washington, LMT',
    title: 'Wellness & Lymphatic Specialist',
    image: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&q=80&w=600',
    rating: 4.97,
    reviewCount: 73,
    location: 'Miami, FL',
    serviceAreas: ['Miami Beach', 'Brickell', 'Coral Gables'],
    startingPrice: 135,
    availability: 'Available Today',
    offersStudio: false,
    offersInHome: true,
    specialties: ['Lymphatic Drainage', 'Hot Stone', 'Swedish'],
    isMostBooked: false,
    isFeatured: true,
  },
  {
    id: 'therapist-6',
    name: 'James Reynolds, LMT',
    title: 'Pain Management Specialist',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=600',
    rating: 4.89,
    reviewCount: 65,
    location: 'Chicago, IL',
    serviceAreas: ['Loop', 'Lincoln Park', 'Evanston'],
    startingPrice: 125,
    availability: 'Available Friday',
    offersStudio: true,
    offersInHome: true,
    specialties: ['Medical Massage', 'Deep Tissue', 'Postural Realignment'],
    isMostBooked: true,
    isFeatured: false,
  },
];

export const MOCK_TESTIMONIALS: MockTestimonial[] = [
  {
    id: 'test-1',
    customerName: 'Jennifer L.',
    customerLocation: 'Los Angeles, CA',
    rating: 5,
    title: 'Flawless In-Home Experience',
    comment: 'MASSAF made it so simple to find a vetted, professional therapist. Elena arrived on time with a full professional setup. Hands down the best deep tissue session I have had in years.',
    verifiedBooking: true,
    date: '2 days ago',
  },
  {
    id: 'test-2',
    customerName: 'Robert K.',
    customerLocation: 'New York, NY',
    rating: 5,
    title: 'Saved my lower back after marathon training',
    comment: 'The booking experience was effortless and transparent. Knowing therapists are background checked gave my family complete peace of mind.',
    verifiedBooking: true,
    date: '1 week ago',
  },
  {
    id: 'test-3',
    customerName: 'Amanda M.',
    customerLocation: 'San Francisco, CA',
    rating: 5,
    title: 'Clean, professional, and therapeutic',
    comment: 'I love being able to select between studio visits or in-home appointments. The quality of therapists on MASSAF is unmatched.',
    verifiedBooking: true,
    date: '2 weeks ago',
  },
];

export const MOCK_THERAPIST_REVIEWS: MockReview[] = [
  {
    id: 'rev-1',
    therapistId: 'therapist-1',
    therapistName: 'Elena Rostova, LMT',
    customerName: 'Michael B.',
    customerLocation: 'Santa Monica, CA',
    rating: 5,
    date: 'Yesterday',
    comment: 'Elena listened attentively to my chronic neck strain issues and worked out tension I have carried for months. Exceptional professionalism.',
    serviceType: '90 Min Deep Tissue Massage',
  },
  {
    id: 'rev-2',
    therapistId: 'therapist-2',
    therapistName: 'Marcus Vance, LMT',
    customerName: 'Sophia P.',
    customerLocation: 'Manhattan, NY',
    rating: 5,
    date: '3 days ago',
    comment: 'Marcus is a top-tier therapist. His knowledge of sports anatomy helped target my hamstrings perfectly.',
    serviceType: '60 Min Sports Recovery',
  },
  {
    id: 'rev-3',
    therapistId: 'therapist-3',
    therapistName: 'Sarah Chen, CMT',
    customerName: 'David H.',
    customerLocation: 'San Francisco, CA',
    rating: 5,
    date: '4 days ago',
    comment: 'Relaxing environment and masterful technique. Left feeling completely rejuvenated!',
    serviceType: '75 Min Holistic Bodywork',
  },
];
